### ISSUE TITLE
API Error

### ISSUE THREAD

**Issue by julianne-bulatao** [tgherzog/wbgapi#18]
I receive this when I try to run code that uses the WBGAPI:

"APIError: [400] Bad Request (https://api.worldbank.org/v2/en/sources/all?per_page=1000&databid=y&page=1&format=json)"

I'm just wondering if there is an issue regarding the WBGAPI communicating with the World Bank servers or is it just the World Bank itself, where the servers are down? This has been going on for a couple of days. If you can, can you please give a status update to let us know when the API will be running again. Thank you in advance.

**Comment by tgherzog** [comment]
I've confirmed this is a problem in the API not the python module and alerted the IT team at the World Bank. Should be back online later this morning.
