### ISSUE TITLE
`wb.data.DataFrame()` generates a warning message

### ISSUE THREAD

**Issue by spring-haru** [tgherzog/wbgapi#23]
I tried [wbgapi](https://github.com/tgherzog/wbgapi)/[examples](https://github.com/tgherzog/wbgapi/tree/master/examples)/wbgapi-quickstart.ipynb. The function
```
wb.data.DataFrame()
``` 
generates the following warning
```
FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  dummy = pd.Series()    # empty series - never assigned actual values
```

**Comment by tgherzog** [comment]
Thanks for the pull request. I've incorporated in the latest release
