### ISSUE TITLE
economies information in pd.Series() format

### ISSUE THREAD

**Issue by matteo-ticli** [tgherzog/wbgapi#27]
Good evening, 

I am trying to pull out information regarding economies using the module economy.Series()

however, I am not able to gather 'region' and 'incomeLevel' that are only available using the module economy.info().

Is there a workaround to this problem? I would like to use for my analysis also the IncomeLevel.

Thank you in advance

**Comment by tgherzog** [comment]
A pandas Series by definition is only one column. Try `economy.DataFrame()`
