### ISSUE TITLE
Attributions: Bibtex Citation

### ISSUE THREAD

**Issue by mirbehroznoor** [tgherzog/wbgapi#32]
Thanks for the amazing work. I have been using the wbgapi for my project's data analysis and also in plotly dash app. I would like to cite the module in my project. 

Since there are no citation guidelines available, looking around the internet, I found: https://cran.r-project.org/web/packages/pwt9/citation.html

I wrote something likewise:

 ````
@Electronic{WorldBank2021WDI,
  organization={The World Bank},
  year={2021},
  title={World Development Indicators},
  note={{accessed via wbgapi python module}},
  url={https://databank.worldbank.org/home},
}

@Manual{wbgapi1012herzog,
  title={{Wbgapi}},
  author={Tim Herzog},
  year=2022,
  date={Jul 5},
  note="Python Module Version: 1.0.12
                  \url{https://pypi.org/project/wbgapi/}",
  url={https://github.com/tgherzog/wbgapi},
}
````

Thank you and would be better if there is an official citation format available.

regards,
Behroz

**Comment by tgherzog** [comment]
wbgapi is a data interface, not a data source. Normally you should cite the source of the data you are using. For instance, if you're accessing population data from the World Development Indicators you would cite as follows or something similar:

Source: World Development Indicators, World Bank. Accessed on [date]

For other options, try googling "how to cite World Bank Data" or contact data@worldbank.org.
