### ISSUE TITLE
issues when convert Taiwan to TWN

### ISSUE THREAD

**Issue by Fisher-Yu-FT** [tgherzog/wbgapi#34]
Seems that we cannot convert Taiwan to TWN now? It has been working for the last two years

In [25]:
b = wb.economy.coder(['Taiwan','india'])

Out[25]: 
ORIGINAL NAME    WBG NAME    ISO_CODE
---------------  ----------  ----------
Taiwan
india            India       IND

**Comment by tgherzog** [comment]
It appears TWN is no longer in the API, at least for the WDI, which means there is nothing to code against. I’ve asked the Bank’s data team for more information.
