### ISSUE TITLE
issue trying to get data from WDI

### ISSUE THREAD

**Issue by wxinl** [tgherzog/wbgapi#35]
I tried to fetch NV.AGR.TOTL.ZS - Agriculture, value added (% of GDP) from WDI (db=2) or WDI archives (db=57), 
my code was `wb.data.DataFrame('NV.AGR.TOTL.ZS', db=2)`

but I got this error: 
APIResponseError: APIError: JSON decoding error (https://api.worldbank.org/v2/en/sources/57/series/NV.AGR.TOTL.ZS/country/all/time/all?per_page=1000&page=1&format=json)

**Comment by tgherzog** [comment]
It appears the API is down on the World Bank side, and currently redirecting to a different portal. I've alerted the support team to the issue.
